# matrix-build/environment-matrix.yml
# Minimal environment for matrix testing

name: quantx-matrix
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - nodejs>=18
  - pip
  # C++ libraries only
  - libta-lib
  - postgresql
  - redis
  # Core Python deps
  - click
  - rich
  - python-dotenv
  - requests
  - flask
  - flask-socketio
  - flask-cors
  - eventlet
  - pip:
    - -e .
