# matrix-build/conda-recipe/conda_build_config.yaml
# Matrix build configuration for testing different combinations

python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13

nodejs:
  - 18
  - 20
  - 22
  - 24

openssl:
  - 1.1.1
  - 3.0

numpy:
  - 1.22
  - 1.24

# Pin problematic packages to stable versions
libta_lib:
  - "*"
  
redis:
  - "*"
  
postgresql:
  - "*"
