# conda-recipe/meta.yaml

package:
  name: quantx
  version: 0.0.4

source:
  path: ../

build:
  number: 0
  script: |
    cd frontend && npm install && npm run build && cd ..
    pip install .

requirements:
  build:
    - python >=3.10
    - pip
    - nodejs
  run:
    - python >=3.10
    - flask
    - flask-socketio
    - flask-cors
    - eventlet
    - redis
    - h5py
    - psycopg2
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - plotly
    - statsmodels
    - gym
    - keras
    - tensorflow
    - pytorch
    - mlflow
    - vectorbt
    - quantlib
    - QuantLib
    - cudatoolkit
    - cupy
    - numba
    # - opengl          # remove
    - ta-lib
    - libta-lib
    - pyopengl
    - jupyter
    - jupyterlab
    - notebook
    - postgresql
    - click
    - rich
    - pytest
    - pyzmq
    - spyder
   # - vscode
   # - orange3
    - glueviz
    - qtconsole
    - anaconda-navigator
    - xlwings

test:
  commands:
    - quantx --help
    - python -c "import flask; import pandas; import quantx"
    - jupyter --version

about:
  home: https://github.com/quantDIY/QuantX
  license: CC-BY-NC-4.0
  summary: "QuantX - Open Source Software for the DIY Quant Revolution"

extra:
  recipe-maintainers:
    - quantDIY
