name: QuantX Matrix Build

on:
  workflow_dispatch:  # Manually triggerable
  push:
    branches:
      - matrix-build

jobs:
  matrix-conda-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        nodejs-version: ["18", "20"]
        openssl-version: ["1.1.1", "3.0"]
        exclude:
          # Exclude known failing combinations
          - python-version: "3.11"
            openssl-version: "1.1.1"

    name: "Python ${{ matrix.python-version }}, Node ${{ matrix.nodejs-version }}, OpenSSL ${{ matrix.openssl-version }}"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults

      - name: Install conda-build
        shell: bash -l {0}
        run: |
          mamba install -y conda-build anaconda-client

      - name: Build conda package
        shell: bash -l {0}
        run: |
          conda build ./matrix-build/conda-recipe \
            --python ${{ matrix.python-version }} \
            --variants "{\"openssl\": [\"${{ matrix.openssl-version }}\"], \"nodejs\": [\"${{ matrix.nodejs-version }}\"]}"

      - name: Test local installation
        shell: bash -l {0}
        run: |
          # Install the built package locally to verify it works
          mamba install -y --use-local quantx-core
          # Verify CLI is accessible
          quantx version

      - name: Upload package artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: quantx-core-py${{ matrix.python-version }}-node${{ matrix.nodejs-version }}-ssl${{ matrix.openssl-version }}
          path: /usr/share/miniconda3/envs/test/conda-bld/*/quantx-core-*.tar.bz2
